version: "3.9"

services:
  eshopdb:
    image: postgres

  distributedCache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:24.0.3
volumes:
  postgres_eshopdb:    
  


