version: "3.9"

services:
  eshopdb:
    image: postgres

  distributedCache:
    image: redis

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:management

volumes:
  postgres_eshopdb:    
  


